Add of firebase authentification, setup of cloud firestore
The authentication should work (can't verify it yet since the
initialisation of the firestore database don't work). The initialisation
of the database fails for some reason with a java.lang.NoClassDefFoundError.